#!/bin/sh

function pin_volume() {
  while true; do
    osascript -e "set Volume 10"
    sleep 1
  done
}

afplay ~/Music/push-it.mp3 &
echo "$!" > .git/pit_1

pin_volume &
echo "$!" > .git/pit_2

exit 0
