#!/bin/sh

declare -a songs=('push-it.mp3' 'push-it-to-the-limit.mp3')
index=`jot -r 1 0 $((${#songs[@]} - 1))`
selected_song=${songs[index]}

function pin_volume() {
  while true; do
    osascript -e "set Volume 10"
    sleep 1
  done
}

afplay ~/Music/$selected_song &
echo "$!" > .git/pit_1

pin_volume &
echo "$!" > .git/pit_2

exit 0
